{% set version = "4.0.1" %}

package:
  name: billiard
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/billiard/billiard-{{ version }}.tar.gz
  sha256: 734d95d12f5c1dbe6256606e751b5eebec66e6c30387415daaf01baec1abc9a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - billiard
    - billiard.dummy

about:
  home: https://github.com/celery/billiard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes
  dev_url: https://github.com/celery/billiard

extra:
  recipe-maintainers:
    - kwilcox
    - igortg
