{% set version = "4.2.2" %}

package:
  name: billiard
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/billiard/billiard-{{ version }}.tar.gz
  sha256: e815017a062b714958463e07ba15981d802dc53d41c5b69d28c5a7c238f8ecf3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - billiard
    - billiard.dummy

about:
  home: https://github.com/celery/billiard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes
  dev_url: https://github.com/celery/billiard

extra:
  recipe-maintainers:
    - efiop
    - rxm7706
    - kwilcox
    - igortg
