{% set version = "3.6.0.0" %}

package:
  name: billiard
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/billiard/billiard-{{ version }}.tar.gz
  sha256: 756bf323f250db8bf88462cd042c992ba60d8f5e07fc5636c24ba7d6f4261d84

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - billiard
    - billiard.dummy

about:
  home: https://github.com/celery/billiard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes
  dev_url: https://github.com/celery/billiard

extra:
  recipe-maintainers:
    - kwilcox
    - igortg
