{% set version = "3.6.1.0" %}

package:
  name: billiard
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/billiard/billiard-{{ version }}.tar.gz
  sha256: b8809c74f648dfe69b973c8e660bcec00603758c9db8ba89d7719f88d5f01f26

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - billiard
    - billiard.dummy

about:
  home: https://github.com/celery/billiard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes
  dev_url: https://github.com/celery/billiard

extra:
  recipe-maintainers:
    - kwilcox
