travis:
  secure:
    BINSTAR_TOKEN: WqZ+yOFDnFQVeaHOvpo/S1TWPsaFVHlsZ/DpuFJKFgBVQzUBM7b1u/VBSWh2qaZplxERWIxzeGspzHlXaKa59YbybZ3pOgSU3AfbGKdsqqCfOnGyFYidvxn/m2voindO9d+0LXDLkwvdTwP9Oi7Hxw6p3DUq0OkWEChABTc0h6imtrXF75u2rfUQs1v1/Mw6h+aUr/El6q3C88rXJnUYoj7iArCduNzfz7OOU9hqHI0zufn8CuHGyW5XNQMskxqJOxaRk0kiTTlm/WtD9BlJsPRq+5M+RpcSFFfNCk1uKz/zulpdyTz7nq2/kGe16oVondgdmFHTWciVVLm6HVz195c3Uxmtta34oSXm8NyD8nbrHqHG0YZ8NrzbCeHX4KGHD4E+dN4olfRTjP1u4wzY7kmZLYefOrwS+Bx45ypNf7h5tnPKm3OXOfjGQgZw/IrwM12E10uRwJ+LS0mTdoxpKUTBmj6hNAkD5WxXLTsRUaPW9VdgXv9cQUUMNq1rcrzYgr85qeY92DObfpM7bfmV7QxvZPmj6u5T3fGIcy3N1b0v0q6xGzQcY18+dGQLEcmefLU4M/8UNhq1WsHBS67cXgcViSgfUsTPxZc3QxJayK7/cqar9Yu3LIqjPI5Mr7YgcD/+88Hfxypjeo4OFgkFxt3ruYXD/0Tns+rtdY8YgQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
